name: deploy_to_dev

concurrency: 1

on:
  workflow_dispatch

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID}}

jobs:
  deploy:
    environment: dev
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: |
          databricks bundle validate -t "dev" --var="env=dev"

      - run: |
          databricks bundle deploy -t "dev" --var="env=dev"
         
